import type { Achievement, UserStats } from '@/types'
import { LEVELS } from './gameLogic'

// Próg XP danego poziomu z kanonicznej tabeli LEVELS — żeby osiągnięcia
// „poziom N" nie rozjeżdżały się z faktycznymi progami. Wcześniej zahardkodowane
// 12000/52000/129000 odpalały odpowiednio na poziomie 8/17/25, nie 10/20/29.
const lvlXP = (n: number): number => LEVELS.find(l => l.level === n)?.xpRequired ?? 0

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_day',
    title: 'Pierwszy krok',
    description: 'Zalogowałaś swój pierwszy dzień w Projekcie 30.',
    icon: '🌱',
    xpReward: 100,
    condition: (s) => s.totalDaysLogged >= 1,
    progress: (s) => ({ current: Math.min(s.totalDaysLogged, 1), target: 1, label: 'dni' }),
  },
  {
    id: 'week_1',
    title: 'Pierwszy tydzień',
    description: '7 dni z rzędu — rutyna zaczyna działać.',
    icon: '🕯️',
    xpReward: 200,
    condition: (s) => s.currentStreak >= 7,
    progress: (s) => ({ current: Math.min(s.currentStreak, 7), target: 7, label: 'dni z rzędu' }),
  },
  {
    id: 'month_1',
    title: 'Pierwszy miesiąc',
    description: '30 dni w projekcie. Jesteś poważna.',
    icon: '🌿',
    xpReward: 500,
    condition: (s) => s.totalDaysLogged >= 30,
    progress: (s) => ({ current: Math.min(s.totalDaysLogged, 30), target: 30, label: 'dni' }),
  },
  {
    id: 'streak_30',
    title: 'Nieugięta',
    description: '30 dni z rzędu bez przerwy.',
    icon: '🔥',
    xpReward: 750,
    condition: (s) => s.currentStreak >= 30,
    progress: (s) => ({ current: Math.min(s.currentStreak, 30), target: 30, label: 'dni z rzędu' }),
  },
  {
    id: 'streak_100',
    title: 'Sto dni bez odwrotu',
    description: 'Stuodniowa passa. To już charakter.',
    icon: '💫',
    xpReward: 2000,
    condition: (s) => s.currentStreak >= 100,
    progress: (s) => ({ current: Math.min(s.currentStreak, 100), target: 100, label: 'dni z rzędu' }),
  },
  {
    id: 'no_impulse_7',
    title: 'Pani swoich impulsów',
    description: '7 dni bez impulsywnego kontaktu z byłym.',
    icon: '🧊',
    xpReward: 300,
    condition: (s) => s.totalRulesKept >= 21,
    progress: (s) => ({ current: Math.min(s.totalRulesKept, 21), target: 21, label: 'zasad przestrzeganych' }),
  },
  {
    id: 'quests_10',
    title: 'Poszukiwaczka',
    description: 'Ukończono 10 questów.',
    icon: '⚔️',
    xpReward: 200,
    condition: (s) => s.totalQuestsCompleted >= 10,
    progress: (s) => ({ current: Math.min(s.totalQuestsCompleted, 10), target: 10, label: 'questów' }),
  },
  {
    id: 'quests_50',
    title: 'Zdobywczyni',
    description: 'Ukończono 50 questów.',
    icon: '🏆',
    xpReward: 800,
    condition: (s) => s.totalQuestsCompleted >= 50,
    progress: (s) => ({ current: Math.min(s.totalQuestsCompleted, 50), target: 50, label: 'questów' }),
  },
  {
    id: 'side_quest_5',
    title: 'Przygodniczka',
    description: 'Ukończono 5 side questów.',
    icon: '🗺️',
    xpReward: 300,
    condition: (s) => s.totalSideQuestsCompleted >= 5,
    progress: (s) => ({ current: Math.min(s.totalSideQuestsCompleted, 5), target: 5, label: 'side questów' }),
  },
  {
    id: 'side_quest_20',
    title: 'Eksploratorka',
    description: 'Ukończono 20 side questów.',
    icon: '🌍',
    xpReward: 800,
    condition: (s) => s.totalSideQuestsCompleted >= 20,
    progress: (s) => ({ current: Math.min(s.totalSideQuestsCompleted, 20), target: 20, label: 'side questów' }),
  },
  {
    id: 'all_pillars',
    title: 'Holistyczna',
    description: 'Zdobyłaś XP w każdym z 7 filarów.',
    icon: '♾️',
    xpReward: 500,
    condition: (s) => Object.values(s.pillarXP).every(xp => xp > 0),
    progress: (s) => ({
      current: Object.values(s.pillarXP).filter(xp => xp > 0).length,
      target: 7,
      label: 'filarów aktywnych',
    }),
  },
  {
    id: 'level_10',
    title: 'Wchodząca na orbitę',
    description: 'Osiągnięto poziom 10 — Pewna.',
    icon: '🪐',
    xpReward: 300,
    condition: (s) => s.totalXP >= lvlXP(10),
    progress: (s) => ({ current: Math.min(s.totalXP, lvlXP(10)), target: lvlXP(10), label: 'XP' }),
  },
  {
    id: 'level_20',
    title: 'Premium Woman',
    description: 'Osiągnięto poziom 20 — Wartościowa.',
    icon: '💎',
    xpReward: 1000,
    condition: (s) => s.totalXP >= lvlXP(20),
    progress: (s) => ({ current: Math.min(s.totalXP, lvlXP(20)), target: lvlXP(20), label: 'XP' }),
  },
  {
    id: 'level_29',
    title: 'Prawie Królowa',
    description: 'Poziom 29. Jeden poziom do finału.',
    icon: '👑',
    xpReward: 2000,
    condition: (s) => s.totalXP >= lvlXP(29),
    progress: (s) => ({ current: Math.min(s.totalXP, lvlXP(29)), target: lvlXP(29), label: 'XP' }),
  },
  {
    id: 'level_30',
    title: 'Natalia 30',
    description: 'Finał projektu. Wszystko, czym się stałaś, jest teraz Twoje.',
    icon: '👸',
    xpReward: 3000,
    condition: (s) => s.totalXP >= lvlXP(30),
    progress: (s) => ({ current: Math.min(s.totalXP, lvlXP(30)), target: lvlXP(30), label: 'XP' }),
  },
  {
    id: 'routines_100',
    title: 'Mistrzyni rutyny',
    description: '100 elementów rutyny ukończone.',
    icon: '🌅',
    xpReward: 500,
    condition: (s) => s.totalRoutinesCompleted >= 100,
    progress: (s) => ({ current: Math.min(s.totalRoutinesCompleted, 100), target: 100, label: 'elementów rutyny' }),
  },

  // ── Ukryte osiągnięcia (hidden: true) ────────────────────────────
  // Nie są zapowiadane — pokazują się jako niespodzianka po spełnieniu warunku.

  {
    id: 'streak_3',
    title: 'Trzy w rządzie',
    description: '3 dni z rzędu. Mała passa, ale każda wielka zaczyna się tutaj.',
    icon: '🌙',
    xpReward: 75,
    hidden: true,
    streakBased: true,
    condition: (s) => s.currentStreak >= 3,
    progress: (s) => ({ current: Math.min(s.currentStreak, 3), target: 3, label: 'dni z rzędu' }),
  },
  {
    id: 'streak_14',
    title: 'Dwa tygodnie',
    description: '14 dni bez zatrzymania. Już nie testujesz — budujesz.',
    icon: '🌒',
    xpReward: 350,
    hidden: true,
    streakBased: true,
    condition: (s) => s.currentStreak >= 14,
    progress: (s) => ({ current: Math.min(s.currentStreak, 14), target: 14, label: 'dni z rzędu' }),
  },
  {
    id: 'streak_21',
    title: 'Nawyk utrwalony',
    description: '21 dni. Nauka mówi, że tyle potrzeba żeby nawyk się zakorzenił. Twój właśnie to zrobił.',
    icon: '🧠',
    xpReward: 500,
    hidden: true,
    streakBased: true,
    condition: (s) => s.currentStreak >= 21,
    progress: (s) => ({ current: Math.min(s.currentStreak, 21), target: 21, label: 'dni z rzędu' }),
  },
  {
    id: 'streak_50',
    title: 'Połowa bez odwrotu',
    description: '50 dni z rzędu. W tym miejscu projektu to już nie wytrwałość — to kim jesteś.',
    icon: '🔮',
    xpReward: 1200,
    hidden: true,
    streakBased: true,
    condition: (s) => s.currentStreak >= 50,
    progress: (s) => ({ current: Math.min(s.currentStreak, 50), target: 50, label: 'dni z rzędu' }),
  },
  {
    id: 'first_side_quest',
    title: 'Ciekawość prowadzi',
    description: 'Pierwszy side quest ukończony. Wyszłaś poza minimum.',
    icon: '✨',
    xpReward: 100,
    hidden: true,
    condition: (s) => s.totalSideQuestsCompleted >= 1,
    progress: (s) => ({ current: Math.min(s.totalSideQuestsCompleted, 1), target: 1, label: 'side questów' }),
  },
  {
    id: 'first_weekly_review',
    title: 'Zaczęłaś patrzeć',
    description: 'Pierwsza recenzja tygodniowa. Kobiety, które wygrywają, robią właśnie to.',
    icon: '🔍',
    xpReward: 150,
    hidden: true,
    condition: (s) => (s.reviewedWeeks?.length ?? 0) >= 1,
    progress: (s) => ({ current: Math.min(s.reviewedWeeks?.length ?? 0, 1), target: 1, label: 'przeglądów' }),
  },
  {
    id: 'monthly_review_1',
    title: 'Księżycowa analiza',
    description: 'Pierwszy miesięczny przegląd. Patrzysz na siebie z dystansu.',
    icon: '🌕',
    xpReward: 250,
    hidden: true,
    condition: (s) => (s.reviewedMonths?.length ?? 0) >= 1,
    progress: (s) => ({ current: Math.min(s.reviewedMonths?.length ?? 0, 1), target: 1, label: 'przeglądów' }),
  },
  {
    id: 'xp_1000',
    title: 'Tysiąc mocy',
    description: 'Pierwsze 1000 XP. Dowód, że działasz.',
    icon: '⚡',
    xpReward: 100,
    hidden: true,
    condition: (s) => s.totalXP >= 1000,
    progress: (s) => ({ current: Math.min(s.totalXP, 1000), target: 1000, label: 'XP' }),
  },
  {
    id: 'xp_5000',
    title: 'Pięć tysięcy',
    description: '5000 XP. Nie każda zaczyna, jeszcze mniej dociera tutaj.',
    icon: '💥',
    xpReward: 200,
    hidden: true,
    condition: (s) => s.totalXP >= 5000,
    progress: (s) => ({ current: Math.min(s.totalXP, 5000), target: 5000, label: 'XP' }),
  },
  {
    id: 'rules_50',
    title: 'Tarcza',
    description: '50 razy wybrałaś siebie. Granica stała się częścią Ciebie.',
    icon: '🛡️',
    xpReward: 400,
    hidden: true,
    condition: (s) => s.totalRulesKept >= 50,
    progress: (s) => ({ current: Math.min(s.totalRulesKept, 50), target: 50, label: 'zasad' }),
  },
  {
    id: 'rules_100',
    title: 'Niezłomna',
    description: '100 zasad przestrzeganych. To już nie reguła — to charakter.',
    icon: '⚔️',
    xpReward: 800,
    hidden: true,
    condition: (s) => s.totalRulesKept >= 100,
    progress: (s) => ({ current: Math.min(s.totalRulesKept, 100), target: 100, label: 'zasad' }),
  },
  {
    id: 'days_60',
    title: 'Dwa miesiące',
    description: '60 zalogowanych dni. Projekt stał się Twoim życiem.',
    icon: '🌸',
    xpReward: 400,
    hidden: true,
    condition: (s) => s.totalDaysLogged >= 60,
    progress: (s) => ({ current: Math.min(s.totalDaysLogged, 60), target: 60, label: 'dni' }),
  },

  // ── Behawioralne — wzorce zachowań ───────────────────────────────

  // Ghost Protocol — zachowanie
  {
    id: 'ghost_5',
    title: 'Tarcza aktywna',
    description: '5 razy aktywowałaś Ghost Protocol. Impuls próbował — przegrał.',
    icon: '🛡️',
    xpReward: 250,
    hidden: true,
    condition: (s) => (s.totalGhostProtocols ?? 0) >= 5,
    progress: (s) => ({ current: Math.min(s.totalGhostProtocols ?? 0, 5), target: 5, label: 'aktywacji GP' }),
  },
  {
    id: 'ghost_10',
    title: 'Niezłomna tarcza',
    description: '10 zwycięstw Ghost Protocol. To nie przypadek — to wzorzec.',
    icon: '⚔️',
    xpReward: 500,
    hidden: true,
    condition: (s) => (s.totalGhostProtocols ?? 0) >= 10,
    progress: (s) => ({ current: Math.min(s.totalGhostProtocols ?? 0, 10), target: 10, label: 'aktywacji GP' }),
  },
  {
    id: 'ghost_25',
    title: 'Protokół stał się instynktem',
    description: '25 aktywacji Ghost Protocol. To już nie narzędzie — to Ty.',
    icon: '🔰',
    xpReward: 1000,
    hidden: true,
    condition: (s) => (s.totalGhostProtocols ?? 0) >= 25,
    progress: (s) => ({ current: Math.min(s.totalGhostProtocols ?? 0, 25), target: 25, label: 'aktywacji GP' }),
  },
  {
    id: 'ghost_streak_7',
    title: 'Tydzień poza zasięgiem',
    description: 'Ghost Protocol aktywny 7 dni z rzędu. Granica stała się murem.',
    icon: '🌑',
    xpReward: 800,
    hidden: true,
    streakBased: true,
    condition: (s) => (s.consecutiveGhostDays ?? 0) >= 7,
    progress: (s) => ({ current: Math.min(s.consecutiveGhostDays ?? 0, 7), target: 7, label: 'dni GP z rzędu' }),
  },

  // Tryb normalny — bez taryfy ulgowej
  {
    id: 'no_minimum_7',
    title: 'Żadnych taryf ulgowych',
    description: '7 dni z rzędu pełna rutyna, bez trybu minimum. To jest siła.',
    icon: '💪',
    xpReward: 400,
    hidden: true,
    streakBased: true,
    condition: (s) => (s.consecutiveNormalDays ?? 0) >= 7,
    progress: (s) => ({ current: Math.min(s.consecutiveNormalDays ?? 0, 7), target: 7, label: 'dni bez minimum' }),
  },
  {
    id: 'no_minimum_30',
    title: 'Miesiąc bez kompromisów',
    description: '30 dni z rzędu bez trybu minimum. Zdecydowałaś, kim jesteś.',
    icon: '🏔️',
    xpReward: 1500,
    hidden: true,
    streakBased: true,
    condition: (s) => (s.consecutiveNormalDays ?? 0) >= 30,
    progress: (s) => ({ current: Math.min(s.consecutiveNormalDays ?? 0, 30), target: 30, label: 'dni bez minimum' }),
  },

  // Rekord dzienny XP
  {
    id: 'day_xp_150',
    title: 'Dzień pełnej mocy',
    description: 'Zdobyłaś 150+ XP w jednym dniu. Pełna mobilizacja.',
    icon: '🌟',
    xpReward: 200,
    hidden: true,
    condition: (s) => (s.highestDayXP ?? 0) >= 150,
  },
  {
    id: 'day_xp_250',
    title: 'Bez hamulców',
    description: '250+ XP w ciągu jednego dnia. Tak właśnie wygląda Ty na 100%.',
    icon: '💫',
    xpReward: 500,
    hidden: true,
    condition: (s) => (s.highestDayXP ?? 0) >= 250,
  },

  // Idealna rutyna poranna
  {
    id: 'perfect_morning_3',
    title: 'Poranny rytuał',
    description: '3 dni z rzędu kompletna rutyna poranna. Poranek jest Twój.',
    icon: '🌄',
    xpReward: 300,
    hidden: true,
    streakBased: true,
    condition: (s) => (s.consecutivePerfectMornings ?? 0) >= 3,
    progress: (s) => ({ current: Math.min(s.consecutivePerfectMornings ?? 0, 3), target: 3, label: 'idealne poranki z rzędu' }),
  },
  {
    id: 'perfect_morning_7',
    title: 'Mistrzyni poranka',
    description: '7 dni z rzędu z idealną rutyną poranną. Budzisz się jako ona.',
    icon: '☀️',
    xpReward: 700,
    hidden: true,
    streakBased: true,
    condition: (s) => (s.consecutivePerfectMornings ?? 0) >= 7,
    progress: (s) => ({ current: Math.min(s.consecutivePerfectMornings ?? 0, 7), target: 7, label: 'idealne poranki z rzędu' }),
  },
]
