import type { Achievement, UserStats } from '@/types'

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_day',
    title: 'Pierwszy krok',
    description: 'Zalogowałaś swój pierwszy dzień w Projekcie 30.',
    icon: '🌱',
    xpReward: 100,
    condition: (s) => s.totalDaysLogged >= 1,
    progress: (s) => ({ current: Math.min(s.totalDaysLogged, 1), target: 1, label: 'dni' }),
  },
  {
    id: 'week_1',
    title: 'Pierwszy tydzień',
    description: '7 dni z rzędu — rutyna zaczyna działać.',
    icon: '🕯️',
    xpReward: 200,
    condition: (s) => s.currentStreak >= 7,
    progress: (s) => ({ current: Math.min(s.currentStreak, 7), target: 7, label: 'dni z rzędu' }),
  },
  {
    id: 'month_1',
    title: 'Pierwszy miesiąc',
    description: '30 dni w projekcie. Jesteś poważna.',
    icon: '🌿',
    xpReward: 500,
    condition: (s) => s.totalDaysLogged >= 30,
    progress: (s) => ({ current: Math.min(s.totalDaysLogged, 30), target: 30, label: 'dni' }),
  },
  {
    id: 'streak_30',
    title: 'Nieugięta',
    description: '30 dni z rzędu bez przerwy.',
    icon: '🔥',
    xpReward: 750,
    condition: (s) => s.currentStreak >= 30,
    progress: (s) => ({ current: Math.min(s.currentStreak, 30), target: 30, label: 'dni z rzędu' }),
  },
  {
    id: 'streak_100',
    title: 'Sto dni bez odwrotu',
    description: 'Stuodniowa passa. To już charakter.',
    icon: '💫',
    xpReward: 2000,
    condition: (s) => s.currentStreak >= 100,
    progress: (s) => ({ current: Math.min(s.currentStreak, 100), target: 100, label: 'dni z rzędu' }),
  },
  {
    id: 'no_impulse_7',
    title: 'Pani swoich impulsów',
    description: '7 dni bez impulsywnego kontaktu z byłym.',
    icon: '🧊',
    xpReward: 300,
    condition: (s) => s.totalRulesKept >= 21,
    progress: (s) => ({ current: Math.min(s.totalRulesKept, 21), target: 21, label: 'zasad przestrzeganych' }),
  },
  {
    id: 'quests_10',
    title: 'Poszukiwaczka',
    description: 'Ukończono 10 questów.',
    icon: '⚔️',
    xpReward: 200,
    condition: (s) => s.totalQuestsCompleted >= 10,
    progress: (s) => ({ current: Math.min(s.totalQuestsCompleted, 10), target: 10, label: 'questów' }),
  },
  {
    id: 'quests_50',
    title: 'Zdobywczyni',
    description: 'Ukończono 50 questów.',
    icon: '🏆',
    xpReward: 800,
    condition: (s) => s.totalQuestsCompleted >= 50,
    progress: (s) => ({ current: Math.min(s.totalQuestsCompleted, 50), target: 50, label: 'questów' }),
  },
  {
    id: 'side_quest_5',
    title: 'Przygodniczka',
    description: 'Ukończono 5 side questów.',
    icon: '🗺️',
    xpReward: 300,
    condition: (s) => s.totalSideQuestsCompleted >= 5,
    progress: (s) => ({ current: Math.min(s.totalSideQuestsCompleted, 5), target: 5, label: 'side questów' }),
  },
  {
    id: 'side_quest_20',
    title: 'Eksploratorka',
    description: 'Ukończono 20 side questów.',
    icon: '🌍',
    xpReward: 800,
    condition: (s) => s.totalSideQuestsCompleted >= 20,
    progress: (s) => ({ current: Math.min(s.totalSideQuestsCompleted, 20), target: 20, label: 'side questów' }),
  },
  {
    id: 'all_pillars',
    title: 'Holistyczna',
    description: 'Zdobyłaś XP w każdym z 7 filarów.',
    icon: '♾️',
    xpReward: 500,
    condition: (s) => Object.values(s.pillarXP).every(xp => xp > 0),
    progress: (s) => ({
      current: Object.values(s.pillarXP).filter(xp => xp > 0).length,
      target: 7,
      label: 'filarów aktywnych',
    }),
  },
  {
    id: 'level_10',
    title: 'Wchodząca na orbitę',
    description: 'Osiągnięto poziom 10 — Pewna.',
    icon: '🪐',
    xpReward: 300,
    condition: (s) => s.totalXP >= 12000,
    progress: (s) => ({ current: Math.min(s.totalXP, 12000), target: 12000, label: 'XP' }),
  },
  {
    id: 'level_20',
    title: 'Premium Woman',
    description: 'Osiągnięto poziom 20 — Wartościowa.',
    icon: '💎',
    xpReward: 1000,
    condition: (s) => s.totalXP >= 52000,
    progress: (s) => ({ current: Math.min(s.totalXP, 52000), target: 52000, label: 'XP' }),
  },
  {
    id: 'level_29',
    title: 'Prawie Królowa',
    description: 'Poziom 29. Jeden poziom do finału.',
    icon: '👑',
    xpReward: 2000,
    condition: (s) => s.totalXP >= 129000,
    progress: (s) => ({ current: Math.min(s.totalXP, 129000), target: 129000, label: 'XP' }),
  },
  {
    id: 'level_30',
    title: 'Natalia 30',
    description: 'Finał projektu. Wszystko, czym się stałaś, jest teraz Twoje.',
    icon: '👸',
    xpReward: 3000,
    condition: (s) => s.totalXP >= 140000,
    progress: (s) => ({ current: Math.min(s.totalXP, 140000), target: 140000, label: 'XP' }),
  },
  {
    id: 'routines_100',
    title: 'Mistrzyni rutyny',
    description: '100 elementów rutyny ukończone.',
    icon: '🌅',
    xpReward: 500,
    condition: (s) => s.totalRoutinesCompleted >= 100,
    progress: (s) => ({ current: Math.min(s.totalRoutinesCompleted, 100), target: 100, label: 'elementów rutyny' }),
  },
]
